import Head from 'next/head'
import Link from 'next/link'
import { GetServerSideProps, GetStaticPaths } from 'next'
import styles from '../../../styles/Home.module.css'

export const getServerSideProps: GetServerSideProps = async ({ query }) => {
  console.log(query);
  const { id } = query; 
  const res = await fetch(`https://rickandmortyapi.com/api/character/${id}`,{method: 'GET'})
  const data = await res.json()

   if (!data) {
    return {
      notFound: true,
    }
  }

  return {
    props:{
        data
    }
  }
}

export default function Character( { data }) {
  const { name, image, gender, location, origin, species, status }= data
  console.log(location)
  return (
    <div className={styles.container}>
      <Head>
        <title>Rick and Morty App - { name }</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
          <img src= {image} alt={name}/>
        
          <p className={styles.description}></p>
        
          <h1 className={styles.description}>
             CHARACTER NAME : { name }      
              <ul>
                 Character Profile details:
                <li>
                  Gender: {gender}
                </li>
                <li>
                  Status: {status}
                </li>
                <li>
                  Species: {species}
                </li>
                <li>
                  Origin: {origin?.name}
                </li>
                <li>
                  Location: {location?.name}
                </li>
                  
              </ul>

          </h1>
          
          <button className={styles.button}>
            <Link href="/"
            >
              <a>
                Back to All Characters
              </a>
            </Link>
          </button>

          

      </main>
    </div>
  )
}

//https://rickandmortyapi.com/api/character/1,2,3,4,5,244
